import Head from 'next/head'
import Image from 'next/image'
import { BeakerIcon } from '@heroicons/react/solid'
import { useState, useEffect } from 'react'
import Loading from '../assets/screens/Loading';
import AppBar from '../assets/components/AppBar';
import YoutubeVideo from '../assets/components/YoutubeVideo';
import { MainSection } from '../assets/components/MainSection';

export default function Home() {
  const [progress, setProgress] = useState(0);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar />
      {/* <Loading /> */}
      <MainSection />
      <YoutubeVideo id="Ja9sbrFglPo" title="Curso javascript parte 1" />

    </div>
  )
}
