import Head from 'next/head'
import Image from 'next/image'
import { BeakerIcon } from '@heroicons/react/solid'
import { useState, useEffect } from 'react'
import Loading from '../assets/screens/Loading';

export default function Home() {
  const [progress, setProgress] = useState(0);

  return (
    <div className="bg-gray-900 h-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Loading/> 
    </div>
  )
}
